"""make_run_id_nullable

Revision ID: 1dee230c14d7
Revises: 246e9c9b6842
Create Date: 2026-06-02 21:38:41.769642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1dee230c14d7'
down_revision: Union[str, None] = '246e9c9b6842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'run_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('contacts', 'run_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'run_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('companies', 'run_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
